.\" Manpage for lineprint.
.\" Contact mozdrent@gmail.com.in to correct errors or typos.
.TH man 8 "27 July 2021" "devduild_alpha_0.0.1" "lineprint man page"
.SH NAME
lineprint \- a fast stdout utlilty written in C.
.SH SYNOPSIS
lineprint <filename>
.SH DESCRIPTION
lineprint is a stdout utlilty written in C.
.SH OPTIONS
lineprint does not take any options.
.SH SEE ALSO
https://github.com/BeanGreen247/lineprint
.SH BUGS
.SH AUTHOR
Thomas Mozdren (mozdrent@gmail.com)
